---
title: "Presentación plaza de ayudante doctor"
subtitle: "Universidad Complutense de Madrid" 
author: 
  - name: Nelson Alirio Cruz
    orcid: 0000-0002-7370-5111
    email: nelsonaliriocruz@gmail.com
    affiliations: 
      - name: "Universitat de les Illes Balears"
        city: "Palma, España"
        
format: 
  revealjs:
    theme: solarized #dracula.scss
    fontsize: 2.0em
embed-resources: true
lang: ES
editor: visual
bibliography: references.bib
---

# Introducción

::: callout-note
# Nelson Alirio Cruz Gutierrez

-   Área: Estadística e Investigación Operativa

-   Perfil: Investigación, Docencia, Extensión e Internacionalización
:::

::: callout-important
## Trayectoria

-   Docencia universitaria desde 2014

-   Actividad investigadora desde 2016

-   Actividad profesional desde 2014

-   Experiencia en múltiples instituciones internacionales
:::

# 1. Investigación

## Investigación en diseños experimentales

::: callout-note
-   Tesis de Maestría en Estadística: Diseño de experimentos crossover para datos de conteo.

-   Tesis de Doctorado en Estadística: Analysis of crossover designs with repeated measurements using generalized estimating equations.
:::

::: callout-important
-   @CruzSemi2023, Q1 en Estadística y Probabilidad (Scopus y JCR)

-   @cruz2026 , Q1 en Estadística y Probabilidad (Scopus y JCR).

-   @cruz2023correlation, Q2 en Estadística y Probabilidad (Scopus y JCR).

-   @cruzanalysis, Q2 en Estadística y Probabilidad (Scopus y JCR).

-   @cruz2026crosscarry, Q2 en Software (Scopus y JCR)
:::

## Paquete de R

<iframe src="https://cran.r-project.org/web/packages/CrossCarry/index.html" width="100%" height="400px">

</iframe>

</iframe>

::: callout-tip
# Internacionalización

-   @corea2025effects, @corea2026citrus Ambas Q1 en Ciencias Animales y en Ciencias Veterinarias (Scopus y JCR)
:::

## Investigación en otras Áreas de la Estadística

::: callout-note
# Modelos espaciotemporales autorregresivos

-   @toloza-delgado2025, Q1 en Estadística y Probabilidad (Scopus y JCR)

-   @Toloza2, Q2-Q3 en Estadística y Probabilidad (Scopus y JCR)

-   @azcarate-romero2025, Q2 en Estudios Urbanos (Scopus y JCR)

-   @miro2024data, Capítulo de libro en congreso, Q3 en Ciencias de la computación (SCOPUS)
:::

<iframe src="https://cran.r-project.org/web/packages/spatemR/index.html" width="100%" height="250px">

</iframe>

</iframe>

## Otros trabajos

::: callout-tip
# Proyectos de investigación

-   Análisis estadístico para experimentos agrícolas en suelos heterogéneos: Una alternativa a los diseños en bloques basada en el concepto de agricultura de precisión. @lizarazo2020effect

-   Salud mental y cardiovascular de jóvenes a partir de la fortaleza interior: Estudio de aceptabilidad y factibilidad. “Salud mental y cardiovascular de jóvenes a partir de la fortaleza interior: Estudio de aceptabilidad y factibilidad. @Laila2026, @gonzalez2025changes

-   Realizar la encuesta de movilidad que comprende la encuesta origen destino de hogares eodh y la encuesta origen destino de interceptacion eodi, para bogota y los municipios vecinos de su area de influencia y la actualizacion del modelo de transporte de cuatro etapas del area de estudio. @azcarate-romero2025
:::

# 2. Docencia

## Universitat de les Illes Balears

::: callout-note
# Docencia

-   422 horas de clase entre 2024 y 2025 de Estadística en grados de Biología, Matemáticas, Ingeniería Telemática, Ingeniería Electrónica Industrial y Automática, Medicina.

-   36 horas de clase en Master de Nutrigenómica.

-   Dirección de 6 TFGs del grado de matemáticas, y tribunal en 7 TFGs de matemáticas.
:::

::: callout-important
# Logros

-   Evaluación docente por encima de 7.5/10 en todas las asignaturas.

-   Material docente creado para las asignaturas: Grado: [Farmacia](https://cruzalirio.github.io/Farmacia/), [Enfermería](https://github.com/Cruzalirio/Unal-Enfermeria-/tree/main), [Biología](https://aprender-uib.github.io/MatesII/). Master: [Statistics Applied to Nutrigenomics](https://cruzalirio.github.io/Nutrigenomics/).

-   Dos proyectos de Innovación Docente. [Disseny de models i impressió 3D per afavorir la visualització espacial en contextos d’aprenentatge matemàtic realista](https://portalinvestigacio.uib.cat/proyectos/1364254/detalle), [Coordinació docent per a un ensenyament holístic al Grau de Farmàcia.](https://portalinvestigacio.uib.cat/proyectos/1349788/detalle)

-   Docencia en Catalán, Inglés y Castellano.
:::

## Universidad Nacional de Colombia

::: callout-note
# Docencia

-   Más de 1600 horas de clase entre 2014 y 2023 de Estadística en grados de Estadística, Física, Matemáticas, Biología, Enfermería, Agronomía, Química, Zootecnia, entre otros.

-   124 horas de clase entre 2022 y 2023 de Estadística en Master en Enfermería y en Salud y Seguridad del trabajo.

-   124 horas de clase entre 2022 y 2023 de Estadística en Doctorado en Enfermería.
:::

::: callout-important
# Logros

-   Evaluación docente por encima de 4 sobre 5 puntos en todas las asignaturas.

-   Cursos de Python y R para extensión en la Universidad.

-   Asesoría Estadística de tesis de Master y de tesis de Doctorado.
:::

## Universidad Central

::: callout-note
# Docencia

-   Más de 1600 horas de clase entre 2016 a 2023 de Estadística en grados de Matemáticas, Biología, Ingeniería industrial, Ingeniería Química, Mercadología, Publicidad y Comunicción Social.

-   Más de 800 horas de clase Estadística para la Maestría en Analítica de Datos.
:::

::: callout-important
# Logros

-   Coordiné durante un año la Maestría en Analítica de Datos, siendo uno de sus creadores.

-   Dirección de 6 TFMs en mi estancia en la Universidad.

-   Análisis de Calidad de programas por medio de encuestas y colección de indicadores.

-   Materiales docentes: Master: [Aprendizaje de Máquina](https://madcentral.github.io/metodosestadisticos/), [Aprendizaje de máquina](https://drive.google.com/drive/folders/1D2fYj_BEuGXC8m6qQNe56El5H6fx53i5?usp=sharing)
:::

::: callout-tip
# Otras universidades

-   Politécnico Grancolombiano. 36 horas de clase en Especialización en Matemática Aplicada.

-   Universidad de Rosario: 60 horas de clase en Maestría en Matemática Aplicada. Dirección de un TFM en Análisis de Datos.
:::

# 3. Formación y trayectoria profesional

## Estudios de Doctorado

::: callout-note
# Doctorado en Ciencias - Estadística

-   Desde el año 2017 al año 2022. Grado en 2023.

-   Beca competitiva predoctoral por la Universidad Nacional de Colombia entre el año 2018 a 2021 (4 años ).

-   Homologado en España por la Universitat de les Illes Balears en 2024.
:::

::: callout-tip
## Contratos profesionales

-   Consultor estadístico y experto tecnológico en el Instituto Colombiano para la Evaluación de la Educación (ICFES) durante 21 meses entre 2021 y 2022.

-   Consultor Análitico y experto en Estadística en Cala Analytics durante 8 meses.
:::

# 4. Internacionalización

## Universitat de les Illes Balears

::: callout-important
# Logros

-   Estancia de Docente Visitante en la Universitat de les Illes Balears desde 2024 hasta 2026.

-   Fundador del grupo MoDAE en la Universidad, y 7 artículos publicados durante mi estancia en esta universidad.

-   Comité asesor de Estadística de las Islas Baleares desde 2024.
:::

<iframe src="https://www.uib.es/personal/ABjQ2NTQ2OA/" width="100%" height="300px">

</iframe>

</iframe>

# 5. Otros méritos

::: callout-note
# Maestría en Ciencias - Estadística

-   Desde el año 2014 al año 2015. Grado en 2016.

-   Beca competitiva predoctoral por la Universidad Nacional de Colombia entre el año 2014 a 2015 (2 años ).

-   Artículo de investigación heredado de esa tesis @cruzanalysis.
:::

::: callout-tip
# Grado en Ciencias - Estadística

-   Desde el año 2009 al año 2013. Grado en 2014.
:::

::: callout-important
# Coordinador de la Maestría en Analítica de Datos

-   Desde el 20 de enero de 2020 hasta el 18 de diciembre de 2020

-   Programación de asignaturas, acompañamiento de estudiantes, contratación de docentes.

-   Gestión de aulas, de cronogramas y de laboratorios de sistemas.
:::

## Bibliografía
